# Generated by Django 5.2.8 on 2025-11-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_entrenador_pokemon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrenador_pokemon',
            old_name='level',
            new_name='age',
        ),
        migrations.RemoveField(
            model_name='entrenador_pokemon',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='entrenador_pokemon',
            name='fechadenacimiento',
        ),
        migrations.AddField(
            model_name='entrenador_pokemon',
            name='pokemons',
            field=models.ManyToManyField(to='pokedex.pokemon'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pokemons/'),
        ),
        migrations.AlterField(
            model_name='entrenador_pokemon',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
