# Generated by Django 5.2.8 on 2026-01-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_pokemon_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrenadorPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('specialty', models.CharField(blank=True, max_length=50, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='trainers/')),
                ('pokemons', models.ManyToManyField(blank=True, to='pokedex.pokemon')),
            ],
        ),
        migrations.DeleteModel(
            name='Entrenador_Pokemon',
        ),
    ]
